language: node_js
node_js:
 - "node"
services:
- postgresql
before_script:
  - psql -c 'create database "housing-test";' -U postgres && knex migrate:latest --env test
script: 'npm run coverage'
after_success: 'npm run coveralls'
env:
- JWT_SECRET=FOOBAR